version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_ecommerce_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - ecommerce

  nginx:
    image: nginx:alpine
    container_name: symfony_ecommerce_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - ecommerce

  mysql:
    image: mysql:8.0
    container_name: symfony_ecommerce_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ecommerce_etudiant
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: ecommerce_user
      MYSQL_PASSWORD: ecommerce_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ecommerce

networks:
  ecommerce:
    driver: bridge

volumes:
  mysql_data:
    driver: local